inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 1.9
  Include:
    - ./**/*.rb
  Exclude:
    - vendor/**/*
    - .vendor/**/*
Metrics/LineLength:
  Max: 140
Style/FileName:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'
    - lib/rspec-puppet-facts-unsupported.rb
    - spec/rspec-puppet-facts-unsupported_spec.rb
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
